### ISSUE TITLE
 作者您好，请问有DQN版本的代码吗 ?  例如 DisCor(DQN)

### ISSUE THREAD

**Issue by sxu-QixianYu** [AIDefender/MyDiscor#1]

**Comment by AIDefender** [comment]
Hi yy1350,

We implemented DQN+ReMERT based on the DQN implementation on [tianshou](https://github.com/thu-ml/tianshou). We made similar modifications to the replay ruffer and the Q-loss as in this repo. Unfortunately, there are no public code available for DisCor+DQN, so we did not implement DQN+ReMERN (as ReMERN is a direct extension to DisCor).
